
[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100


[tool.mypy]
ignore_missing_imports = true
# strict = true

[[tool.mypy.overrides]]
module = ['helloworld.v1.*']
ignore_errors = true
