protobuf_sources(
    name="default",
    grpc=True,
)

protobuf_sources(
    name="grpc_client",
    grpc=True,
    python_resolve="grpc_client",
)

protobuf_sources(
    name="grpc_client_3_10",
    grpc=True,
    python_resolve="grpc_client_3_10",
)
