---
on: [pull_request]
name: Test
jobs:
  test_python:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11.2]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pantsbuild/actions/init-pants@v5-scie-pants
      - name: Test
        run: "pants -V"
      - name: Test
        run: "pants test ::"
      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: dist/coverage/python/coverage.xml
